doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/User/Entity'
                prefix: 'App\User\Entity'
                alias: User
            Maker:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: Maker
            Airport:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Airport/Entity'
                prefix: 'App\Airport\Entity'
                alias: Airport
            Route:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Route/Entity'
                prefix: 'App\Route\Entity'
                alias: Route
            Airline:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Airline/Entity'
                prefix: 'App\Airline\Entity'
                alias: Airline
